development:
  adapter: postgresql
  database: onruby_development
  username: <%= ENV["DB_USERNAME"] || "postgres" %>
  password: <%= ENV["DB_PASSWORD"] || "" %>
  host: <%= ENV["DB_HOST"] || "localhost" %>
  encoding: utf8

test:
  adapter: postgresql
  database: onruby_test
  username: <%= ENV["DB_USERNAME"] || "postgres" %>
  password: <%= ENV["DB_PASSWORD"] || "" %>
  host: <%= ENV["DB_HOST"] || "localhost" %>
  encoding: utf8
